### PR TITLE
Restores panics to #485

### LINKED ISSUE #490: Confirm sdk v0.45.11 upgrade safety
# Problem
https://github.com/cosmos/interchain-security/pull/485 potentially changed provider behavior. Before that PR we panicked for a particular unbonding error, and now we only log an error. To my knowledge this will allow a faulty tx to continue execution. 

# Closing criteria

Either confirm this change in functionality is safe, **and that an error log is noticeable enough for validators**, or change the sdk handler to panic when an error is returned.

# Problem details

See https://github.com/cosmos/interchain-security/pull/485#discussion_r1025698575 

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

### PR DESCRIPTION
**Pull request by jtremback**
Closes #490

### CODE REVIEW

**Review by smarshall-spitzbart — APPROVED** [review]

File: x/ccv/provider/keeper/hooks.go [hunk 1]
```diff
@@ -48,12 +48,12 @@ func (h Hooks) AfterUnbondingInitiated(ctx sdk.Context, ID uint64) error {
 
 	// Set unbondingOp
 	if err := h.k.SetUnbondingOp(ctx, unbondingOp); err != nil {
-		return fmt.Errorf("unbonding op could not be persisted: %w", err)
+		panic(fmt.Errorf("unbonding op could not be persisted: %w", err))
```
Comment (mpoke) [inline x/ccv/provider/keeper/hooks.go:51]: Please add comment explaining why we are panicking.

File: x/ccv/provider/keeper/hooks.go [hunk 2]
```diff
@@ -48,12 +48,12 @@ func (h Hooks) AfterUnbondingInitiated(ctx sdk.Context, ID uint64) error {
...
 	}
 
 	// Call back into staking to tell it to stop this op from unbonding when the unbonding period is complete
 	if err := h.k.stakingKeeper.PutUnbondingOnHold(ctx, ID); err != nil {
-		return fmt.Errorf("unbonding could not be put on hold: %w", err)
+		panic(fmt.Errorf("unbonding could not be put on hold: %w", err))
```
Comment (mpoke) [inline x/ccv/provider/keeper/hooks.go:56]: ditto

**Review by mpoke — APPROVED** [review]
